version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: tdididit-a0_gateway_1
      APP_PORT: 3000

  gateway:
    image: agent0ai/agent-zero:v0.9.8.2
    user: "1000:1000"
    init: true
    volumes:
      - ${APP_DATA_DIR}/data:/a0/usr
    restart: on-failure
