version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: tdididit-a0_gateway_1
      APP_PORT: 50080

  gateway:
    image: agent0ai/agent-zero:v0.9.8.2@sha256:6c56558df02618dcd9fc671de0b081ac7c8dc63d955ae5da55be9805b5f5bfa7
    user: "1000:1000"
    init: true
    volumes:
      - ${APP_DATA_DIR}/data:/a0/usr
    ports:
    	 - 50080:80
    restart: on-failure
    